_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 55
                - 81
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 55
                - 81
            "3":
                - 2
                - 3
                - 8
                - 16
                - 23
                - 55
                - 61
                - 62
            "4": 3.12.6
            "5": 0.18.5
            "8":
                - 1
                - 5
            "10":
                - 17
            "12": 0.18.5
            "13": darwin-arm64
batch_size:
    value: 16
class_weights:
    value:
        "0": 1.1089405835433284
        "1": 0.9105490859966826
epochs:
    value: 50
frozen_layers:
    value: 1
learning_rate:
    value: 0.001
lr_reduce_patience:
    value: 15
