_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.12.6
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 55
                - 81
            "2":
                - 1
                - 2
                - 3
                - 5
                - 53
                - 55
                - 81
            "3":
                - 2
                - 3
                - 8
                - 23
                - 55
                - 62
            "4": 3.12.6
            "5": 0.18.5
            "8":
                - 1
                - 5
            "10":
                - 9
                - 17
            "12": 0.18.5
            "13": darwin-arm64
batch_size:
    value: 16
class_weights:
    value:
        "0": 17066.666666666668
        "1": 0.8113590263691683
        "2": 0.14354221248452786
        "3": 0.46454656807149663
        "4": 7.011297500855871
        "5": 22.70509977827051
        "6": 2.967341852849981
        "7": 326.11464968152865
        "8": 8.026965587520577
        "9": 7.960199004975125
        "10": 8.205128205128204
        "11": 1.3344105918840732
epochs:
    value: 2
learning_rate:
    value: 9.999999747378752e-05
