name: intro_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - jupyter
  - ipython
  - ipykernel
  - gym
  - pip
  - pip:
      - ipython-display