name: pinn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - matplotlib
  - seaborn
  - scipy
  - tqdm
  - tensorflow
  - scikit-learn
  - ipykernel
  - jupyterlab
  - pip
